export { default as Menu } from './Menu/Menu';
export { default as Laurels } from './Laurels/Laurels';
export { default as Intro } from './Intro/Intro';
export { default as Header } from './Header/Header';
export { default as Gallery } from './Gallery/Gallery';
export { default as Footer } from './Footer/Footer';
export { default as Findus } from './Findus/Findus';
export { default as Chef } from './Chef/Chef';
export { default as Aboutus } from './Aboutus/Aboutus';
